### ISSUE TITLE
Bajar el data.json a estructura de base de datos

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/back-invoices#3]
COMO desarrollador QUIERO poder identificar las propidades/columnas necesarias PARA poder guardar los datos en su lugar correspondiente.

Definición de hecho:
Que la estructura del json quede reflejada en el schema de la bd

El archivo data.json se encuentra dentro de [invoice-app.zip](https://discord.com/channels/916074182524174386/1063212906403082322/1063213368816701542)

Relates to #4

**Comment by nsdonato** [comment]
Se pasa a bloqueado porque dependía de la tarea #4 y yo las relacione al revés 😅

**Comment by nsdonato** [comment]
@Jean-Dv si, ya lo tengo anotado, lo vemos hoy en el vivo tranqui, si la 2 esta bloqueada, pasenla para esta columna porfi

**Comment by jpaddeo** [comment]
@nsdonato @Jean-Dv con la info que me pasó @rretta ya pude ejecutar correctamente el seeder y la data ya está en la bd compartida. Generé una PR con un fix al script para que se pueda ejecutar por más que exista la data ya y ajuste el json con los ids posta. Entiendo que podríamos cerrar el issue, pero lo dejo a vuestro criterio.
