### ISSUE TITLE
Configurar BD en Mongo Atlas

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/back-invoices#4]
COMO desarrollador QUIERO dar de alta una bd PARA poder utilizarla en el proyecto

Definición de hecho:
Que los involucrados en el proyecto tengan la configuración necesaria, sin subir info sensible al repositorio.

Relates to #3

**Comment by jpaddeo** [comment]
Pude ejecutar sin errores el seeder (de hecho ya está la data de prueba en la bd). Gracias @rretta !

**Comment by jpaddeo** [comment]
@rretta cierro el issue dado que ya está realizado (y aún sigue abierto y figura en issues del repo)
