### ISSUE TITLE
Crear documentación de endpoints con Swagger

### ISSUE THREAD

**Issue by nsdonato** [nsdonato/back-invoices#7]
COMO desarrollador QUIERO poder instalar las dependencias necesarias PARA poder configurar Swagger o la herramienta elegida para documentar.

Definición de hecho:
Que se vea la documentación de los endpoints de manera correcta.

Relates to #5

**Comment by nsdonato** [comment]
@row-d hola! consulta, esta tarea la tenía asignada yo y ya la había adelantado en mi rama. Se hizo otra por algún motivo?

**Comment by row-d** [comment]
hola, no tenia idea, como vi que en ninguna rama del proyecto estaba lo de swagger y estaba abierta la issue me lo puse hacer

**Comment by nsdonato** [comment]
@row-d entiendo, pero siempre hay que revisar las tareas asignadas, salvo que hagan pair programming, igual debería tenerla la persona que la hace ya que se entiende que el otro ser hace de apoyo moral o ayuda jaj. No te hagas drama, yo me desasigno esta tarea y la seguis vos.
